# RDP Gateway Hosts Configuration
# This file defines which hosts users can connect to through the RDP Gateway

# Host definitions
hosts:
  # Example Windows Server
  - name: "windows-server-01"
    address: "192.168.1.100"
    port: 3389
    description: "Windows Server 2022 - Main Server"
    allowed_users:
      - "admin"
      - "it-staff"
    allowed_groups:
      - "administrators"
      - "remote-users"
    
  # Example Windows Desktop
  - name: "workstation-01"
    address: "192.168.1.150"
    port: 3389
    description: "IT Workstation"
    allowed_users:
      - "admin"
    allowed_groups:
      - "administrators"
    
  # Example server with custom RDP port
  - name: "secure-server"
    address: "192.168.1.200"
    port: 13450  # Custom RDP port as suggested in the EdTech IRL article
    description: "Secure Server with custom RDP port"
    allowed_users:
      - "admin"
      - "security-team"
    allowed_groups:
      - "administrators"
      - "security"
    
  # Example domain controller
  - name: "domain-controller"
    address: "192.168.1.10"
    port: 3389
    description: "Active Directory Domain Controller"
    allowed_users:
      - "admin"
      - "domain-admin"
    allowed_groups:
      - "domain-admins"
    
  # Example development server
  - name: "dev-server"
    address: "192.168.1.250"
    port: 3389
    description: "Development Server"
    allowed_users:
      - "developer"
      - "qa-team"
    allowed_groups:
      - "developers"
      - "qa"

# Global settings
settings:
  # Default RDP port if not specified
  default_port: 3389
  
  # Connection timeout in seconds
  connection_timeout: 30
  
  # Maximum concurrent connections per user
  max_connections_per_user: 3
  
  # Enable logging of connection attempts
  log_connections: true
  
  # Require encryption for all connections
  require_encryption: true
  
  # Network Level Authentication requirement
  require_nla: true
  
  # Certificate validation
  ignore_certificate_errors: false
  
  # Session settings
  idle_timeout: 1800  # 30 minutes
  session_timeout: 28800  # 8 hours
  
  # Security settings
  enable_clipboard: true
  enable_file_transfer: false
  enable_audio: true
  enable_printing: false
  
  # Allowed security protocols
  allowed_protocols:
    - "rdp"
    - "tls"
    - "nla"

# Host groups for easier management
host_groups:
  servers:
    - "windows-server-01"
    - "secure-server"
    - "domain-controller"
  
  workstations:
    - "workstation-01"
  
  development:
    - "dev-server" 