# RDP Gateway Hosts Configuration
# This file defines which hosts users can connect to through the RDP Gateway

# Host definitions
hosts:
  # Your Windows machine at 192.168.1.11
  - name: "WindowsDesktop"
    address: "192.168.1.11"  # Your Windows machine IP
    port: 3389               # Standard RDP port
    description: "Windows Desktop at 192.168.1.11"
    allowed_users:
      - "rdpuser"            # User that will connect through RDP Gateway
      - "admin"
    allowed_groups:
      - "remote-users"
    
    # Optional: Specify credentials for the target Windows machine
    # These are the Windows machine credentials, not the RDP Gateway credentials
    target_credentials:
      username: "your_windows_username"    # Replace with your actual Windows username
      # Password will be prompted during connection for security

# Global settings
settings:
  # Default RDP port if not specified
  default_port: 3389
  
  # Connection timeout in seconds
  connection_timeout: 30
  
  # Maximum concurrent connections per user
  max_connections_per_user: 2
  
  # Enable logging of connection attempts
  log_connections: true
  
  # Require encryption for all connections
  require_encryption: true
  
  # Network Level Authentication requirement (recommended)
  require_nla: true
  
  # Session settings
  idle_timeout: 1800      # 30 minutes
  session_timeout: 14400  # 4 hours
  
  # Security settings for Mac compatibility
  enable_clipboard: true
  enable_file_transfer: true
  enable_audio: true
  enable_printing: true
  
  # Allowed security protocols
  allowed_protocols:
    - "rdp"
    - "tls"
    - "nla"

# Host groups
host_groups:
  windows_hosts:
    - "windows-desktop-11" 