networks:
  guac_cloudflared:
    driver: bridge
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
services:
  guacamole:
    image: cloudflare/cloudflared:2024.11.0
    hostname: cloudflare
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<enter cloudflare token here>
    networks:
      guac_cloudflared:
        ipv4_address: 172.18.0.2
