# RDP Gateway Docker Compose Configuration
# This provides native RDP client access through Cloudflare tunnel

version: '3.8'

networks:
  default:
    name: guac-cloudflare_cloudflared
    external: true

services:
  rdpgw:
    image: bolkedebruin/rdpgw:latest
    hostname: rdpgw
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.5
    ports:
      - "127.0.0.1:${RDPGW_PORT:-3391}:${RDPGW_PORT:-3391}"  # RDP Gateway port (localhost only)
      - "127.0.0.1:${RDPGW_WEB_PORT:-443}:${RDPGW_WEB_PORT:-443}"    # HTTPS port for RDP Gateway web interface
    volumes:
      - rdpgw_config:/opt/rdpgw/config
      - rdpgw_certs:/opt/rdpgw/certs
      - ./logs:/opt/rdpgw/logs
      - ./rdpgw:/opt/rdpgw/conf
    environment:
      - RDPGW_SERVER_CERT=/opt/rdpgw/certs/server.crt
      - RDPGW_SERVER_KEY=/opt/rdpgw/certs/server.key
      - RDPGW_SERVER_PORT=${RDPGW_PORT:-3391}
      - RDPGW_WEB_PORT=${RDPGW_WEB_PORT:-443}
      - RDPGW_ENABLE_AUTH=true
      - RDPGW_AUTH_BACKEND=${RDPGW_AUTH_BACKEND:-local}
      - RDPGW_HOSTS_FILE=/opt/rdpgw/conf/hosts.yaml
      - RDPGW_USERS_FILE=/opt/rdpgw/conf/users.yaml
      - RDPGW_LOG_LEVEL=${RDPGW_LOG_LEVEL:-info}
      - RDPGW_ENABLE_SECURITY=true
      - RDPGW_IDLE_TIMEOUT=${RDPGW_IDLE_TIMEOUT:-1800}
      - RDPGW_SESSION_TIMEOUT=${RDPGW_SESSION_TIMEOUT:-28800}
      # Integration with DUO (if enabled)
      - RDPGW_DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY:-}
      - RDPGW_DUO_SECRET_KEY=${DUO_SECRET_KEY:-}
      - RDPGW_DUO_API_HOSTNAME=${DUO_API_HOSTNAME:-}
      - RDPGW_DUO_APPLICATION_KEY=${DUO_APPLICATION_KEY:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.project=rdpgw"

  # Optional: FreeRDP Gateway (alternative implementation)
  freerdp-gateway:
    image: freerdp/freerdp:latest
    hostname: freerdp-gateway
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.6
    ports:
      - "127.0.0.1:${FREERDP_PORT:-3392}:${FREERDP_PORT:-3392}"
    volumes:
      - freerdp_config:/etc/freerdp
      - ./logs:/var/log/freerdp
      - ./rdpgw:/etc/freerdp/conf
    environment:
      - FREERDP_GATEWAY_PORT=${FREERDP_PORT:-3392}
      - FREERDP_LOG_LEVEL=INFO
      - FREERDP_AUTH_BACKEND=file
      - FREERDP_CONFIG_FILE=/etc/freerdp/conf/gateway.conf
    healthcheck:
      test: ["CMD", "netstat", "-ln", "|", "grep", ":3392"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    profiles:
      - freerdp  # Only start with --profile freerdp

volumes:
  rdpgw_config:
    driver: local
  rdpgw_certs:
    driver: local
  freerdp_config:
    driver: local 