# RDP Gateway Docker Compose Configuration
# This provides native RDP client access through Cloudflare tunnel

networks:
  default:
    name: rdp_cloudflared
    external: true

services:
  rdpgw:
    image: bolkedebruin/rdpgw:latest
    hostname: rdpgw
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.5
    ports:
      - "${RDPGW_PORT:-3391}:${RDPGW_PORT:-3391}"  # RDP Gateway port
      - "${RDPGW_WEB_PORT:-443}:${RDPGW_WEB_PORT:-443}"    # HTTPS port for RDP Gateway web interface
    volumes:
      - rdpgw_config:/opt/rdpgw/config               # Main configuration volume
      - rdpgw_data:/srv/rdpgw                        # Shared RDP Gateway data volume
      - rdpgw_certs:/opt/rdpgw/certs                 # SSL certificates
      - rdpgw_logs:/opt/rdpgw/logs                   # Application logs
      - ./rdpgw:/srv/rdpgw/conf:ro                   # Read-only bind mount for config files
    environment:
      - RDPGW_SERVER_CERT=/opt/rdpgw/certs/server.crt
      - RDPGW_SERVER_KEY=/opt/rdpgw/certs/server.key
      - RDPGW_SERVER_PORT=${RDPGW_PORT:-3391}
      - RDPGW_WEB_PORT=${RDPGW_WEB_PORT:-443}
      - RDPGW_ENABLE_AUTH=true
      - RDPGW_AUTH_BACKEND=${RDPGW_AUTH_BACKEND:-local}
      - RDPGW_HOSTS_FILE=/srv/rdpgw/conf/hosts.yaml
      - RDPGW_USERS_FILE=/srv/rdpgw/conf/users.yaml
      - RDPGW_CONFIG_DIR=/srv/rdpgw/conf
      - RDPGW_DATA_DIR=/srv/rdpgw
      - RDPGW_LOG_LEVEL=${RDPGW_LOG_LEVEL:-info}
      - RDPGW_ENABLE_SECURITY=true
      - RDPGW_IDLE_TIMEOUT=${RDPGW_IDLE_TIMEOUT:-1800}
      - RDPGW_SESSION_TIMEOUT=${RDPGW_SESSION_TIMEOUT:-28800}
      # Integration with DUO (if enabled)
      - RDPGW_DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY:-}
      - RDPGW_DUO_SECRET_KEY=${DUO_SECRET_KEY:-}
      - RDPGW_DUO_API_HOSTNAME=${DUO_API_HOSTNAME:-}
      - RDPGW_DUO_APPLICATION_KEY=${DUO_APPLICATION_KEY:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:${RDPGW_WEB_PORT:-443}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.project=rdpgw"
      - "com.rdpgw.config.dir=/srv/rdpgw"

  # Optional: FreeRDP Gateway (alternative implementation)
  freerdp-gateway:
    image: freerdp/freerdp:latest
    hostname: freerdp-gateway
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.6
    ports:
      - "${FREERDP_PORT:-3392}:${FREERDP_PORT:-3392}"
    volumes:
      - freerdp_config:/etc/freerdp
      - rdpgw_logs:/var/log/freerdp
      - rdpgw_data:/srv/rdpgw:ro                     # Shared RDP Gateway data (read-only)
    environment:
      - FREERDP_GATEWAY_PORT=${FREERDP_PORT:-3392}
      - FREERDP_LOG_LEVEL=INFO
      - FREERDP_AUTH_BACKEND=file
      - FREERDP_CONFIG_FILE=/srv/rdpgw/conf/gateway.conf
      - FREERDP_DATA_DIR=/srv/rdpgw
    healthcheck:
      test: ["CMD", "netstat", "-ln", "|", "grep", ":${FREERDP_PORT:-3392}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    profiles:
      - freerdp  # Only start with --profile freerdp

volumes:
  rdpgw_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/rdpgw/config
  rdpgw_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/rdpgw
  rdpgw_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/rdpgw/certs
  rdpgw_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/rdpgw/logs
  freerdp_config:
    driver: local 