networks:
  cloudflared:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  # All-in-one Guacamole with built-in database and guacd
  guacamole:
    image: ${GUACAMOLE_IMAGE:-abesnier/guacamole:1.5.5-pg15}
    hostname: guacamole
    restart: unless-stopped
    networks:
      cloudflared:
        ipv4_address: 172.18.0.3
    ports: 
      - "8080:8080"
    volumes:
      - guac_config:/config
      - ./logs:/opt/guacamole/logs  # External log directory
      - ./extensions:/opt/guacamole/extensions  # Custom extensions (DUO, etc.)
      - ./branding:/opt/guacamole/branding  # Custom branding assets
    environment:
      # DUO Security 2FA Configuration (optional)
      - DUO_INTEGRATION_KEY=${DUO_INTEGRATION_KEY:-}
      - DUO_SECRET_KEY=${DUO_SECRET_KEY:-}
      - DUO_API_HOSTNAME=${DUO_API_HOSTNAME:-}
      - DUO_APPLICATION_KEY=${DUO_APPLICATION_KEY:-}
      - DUO_ENROLLMENT_URL=${DUO_ENROLLMENT_URL:-}
      # Custom branding configuration
      - CUSTOM_LOGO_PATH=${CUSTOM_LOGO_PATH:-/opt/guacamole/branding/logo.png}
      - CUSTOM_THEME=${CUSTOM_THEME:-default}
      - LOGIN_MESSAGE=${LOGIN_MESSAGE:-Welcome to Guacamole}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/guacamole/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.project=guacamole"

volumes:
  guac_config:
    driver: local
